<h1>Post</h1>

<p>A reader posted an interesting comment to my <a href="http://www.raymondcamden.com/index.cfm/2007/12/5/The-Complete-Guide-to-Adding-Error-Handling-to-Your-ColdFusion-Application">ColdFusion Exception Handling Guide</a>. He had modified his error handling to store the errors in a database. This allowed him to look at history exception information, do trending, etc. But he ran into trouble trying to remove the stack trace from the exception object. Here is an example of that.</p>
<!--more-->
<p>Imagine a simple onError like so:</p>
<code>
&lt;cffunction name="onError" returnType="void" output="false"&gt;
	&lt;cfargument name="exception" required="true"&gt;
	&lt;cfargument name="eventname" type="string" required="true"&gt;
	&lt;cfset structDelete(arguments.exception, "stacktrace")&gt;
	&lt;cfdump var="#exception#"&gt;
	&lt;cfabort&gt;
&lt;/cffunction&gt;
</code>
<p>Doing this causes the error handler itself to barf out: <b>cannot remove properties from a java object</b>. While I knew that Exceptions were Java objects, I had always assumed that when ColdFusion got to it, it was a normal struct. When you cfdump it, you see a struct, which is very different from the normal Java object dump. However, you can see that it is not if you check the class name:</p>
<code>
&lt;cfdump var="#exception.getClass().getName()#"&gt;
</code>
<p>This returns <b>coldfusion.runtime.UndefinedVariableException</b> whereas a &quot;real&quot; structure would return <b>coldfusion.runtime.Struct</b>. Ok, so this implies that cfdump recognizes the ColdFusion exception and massages the output a bit. What happens if we try to duplicate the structure?</p>
<code>
&lt;cfset var ex = duplicate(arguments.exception)&gt;
&lt;cfset structDelete(ex, "stacktrace")&gt;
&lt;cfdump var="#ex#"&gt;
</code>
<p>Unfortunately this returns the exact same error: <b>cannot remove properties from a java object</b>. So we still have a Java object after the duplicate. No surprise there I guess, but if cfdump had a 'hack' for ColdFusion exceptions I thought perhaps duplicate might.</p>
<p>I then tried this variation:</p>
<code>
&lt;cfset var newEx = structNew()&gt;
&lt;cfloop item="key" collection="#arguments.exception#"&gt;
	&lt;cfset newEx[key] = duplicate(arguments.exception[key])&gt;
&lt;/cfloop&gt;
<p>&lt;cfdump var=&quot;#newEx#&quot;&gt;
&lt;cfdump var=&quot;#newex.getClass().getName()#&quot;&gt;
</code></p>
<p>And bam - that did it. So at the key level the values came over correctly. And just to be sure, I then did this:</p>
<code>
&lt;cfset newEx.stackTrace = left(newEx.stackTrace, 100)&gt;
</code>
<p>And bam - that worked perfectly.</p>
<p>Of course, this may be overkill. If you are inserting the values from the exception object into the database, you can simply do the left in your cfquery. So for example, this is fine:</p>
<code>
&lt;cfoutput&gt;#left(arguments.exception.stacktrace,10)#&lt;/cfoutput&gt;
</code>
<p>I'm not modifying the actual Exception object, just the result of getting the string value.</p>
}