<h1>Post</h1>

<p>ColdFusion MX added try/catch to the CFSCRIPT, a welcome addition, but you can't throw an exception, or rethrow. Doing a throw is quite easy if you write a <a href="http://www.cflib.org/udf.cfm/throw">UDF</a> for it. However, rethrow is not so easy. You may think:</p>
<div class="code"><FONT COLOR=MAROON>&lt;cffunction name=<FONT COLOR=BLUE>"rethrow"</FONT>&gt;</FONT><br>
  <FONT COLOR=MAROON>&lt;cfrethrow&gt;</FONT><br>
<FONT COLOR=MAROON>&lt;/cffunction&gt;</FONT></div>
<p>However, this will cause a syntax error since rethrow must be contained inside a cfcatch block. For the heck of it, I tried the following:</p>
<div class="code"><FONT COLOR=MAROON>&lt;cffunction name=<FONT COLOR=BLUE>"rethrow"</FONT>&gt;</FONT><br>
&nbsp;&nbsp;&nbsp;<FONT COLOR=MAROON>&lt;cftry&gt;</FONT><br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<FONT COLOR=MAROON>&lt;cfcatch&gt;</FONT><br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<FONT COLOR=MAROON>&lt;cfrethrow&gt;</FONT><br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<FONT COLOR=MAROON>&lt;/cfcatch&gt;</FONT><br>
&nbsp;&nbsp;&nbsp;<FONT COLOR=MAROON>&lt;/cftry&gt;</FONT><br>
<FONT COLOR=MAROON>&lt;/cffunction&gt;</FONT><br>
<br>
<FONT COLOR=MAROON>&lt;cftry&gt;</FONT><br>
&nbsp;&nbsp;&nbsp;<FONT COLOR=MAROON>&lt;cfscript&gt;</FONT><br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;try {<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;throw(<FONT COLOR=BLUE>"my type"</FONT>,<FONT COLOR=BLUE>"my ex"</FONT>);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;} catch(Exception e) {<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;rethrow();<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<br>
&nbsp;&nbsp;&nbsp;<FONT COLOR=MAROON>&lt;/cfscript&gt;</FONT><br>
&nbsp;&nbsp;&nbsp;<FONT COLOR=MAROON>&lt;cfcatch&gt;</FONT><br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<FONT COLOR=MAROON>&lt;cfoutput&gt;</FONT>exception thrown<FONT COLOR=MAROON>&lt;/cfoutput&gt;</FONT><br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<FONT COLOR=MAROON>&lt;cfdump var=<FONT COLOR=BLUE>"#cfcatch#"</FONT>&gt;</FONT><br>
&nbsp;&nbsp;&nbsp;<FONT COLOR=MAROON>&lt;/cfcatch&gt;</FONT><br>
<FONT COLOR=MAROON>&lt;/cftry&gt;</FONT></div>
<p>What surprised me is that my rethrow UDF noticed an error had occured and automatically entered the cfcatch block.</p>
<p>This had one problem though. I could call rethrow outside of cfcatch. It wouldn't throw an exception, it would simply do nothing. I modified the UDF like so:</p>
<div class="code"><FONT COLOR=MAROON>&lt;cffunction name=<FONT COLOR=BLUE>"rethrow"</FONT>&gt;</FONT><br>
&nbsp;&nbsp;&nbsp;<FONT COLOR=MAROON>&lt;cftry&gt;</FONT><br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<FONT COLOR=MAROON>&lt;cfcatch&gt;</FONT><br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<FONT COLOR=MAROON>&lt;cfrethrow&gt;</FONT><br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<FONT COLOR=MAROON>&lt;/cfcatch&gt;</FONT><br>
&nbsp;&nbsp;&nbsp;<FONT COLOR=MAROON>&lt;/cftry&gt;</FONT><br>
&nbsp;&nbsp;&nbsp;<FONT COLOR=MAROON>&lt;cfthrow type=<FONT COLOR=BLUE>"Context validation error"</FONT> message=<FONT COLOR=BLUE>"Context validation error for CFRETHROW."</FONT>&gt;</FONT><br>
<FONT COLOR=MAROON>&lt;/cffunction&gt;</FONT></div>
<p>You will only get to the end of the UDF when you haven't called rethrow() in a catch block.</p>
<p>p.s. Normally I'd add returnType/output/etc to my code. Don't forget to do so if you actually use the UDFs.</p>
<p>p.s.s. And of course, I'd much prefer it if MACR would simply add throw/rethrow to cfscript. :)</p>
}